### ISSUE TITLE
research Spring IoC container technology

### ISSUE THREAD

**Issue by AdoHe** [AdoHe/RestKiss#1]
RT. Spring IoC container and DI is very suitable for bean definitions management.

**Comment by AdoHe** [comment]
We just need annotation based bean configuration, also service context will act as a bean container. Please refer this: `http://www.tutorialspoint.com/spring/spring_annotation_based_configuration.htm`

**Comment by tyaloo** [comment]
https://github.com/google/guice

**Comment by AdoHe** [comment]
@tyaloo do we need to use guice?

**Comment by AdoHe** [comment]
@tyaloo After think about a while, I think Spring Ioc Container and DI are much more complicated for this simple service framework, so I will remove some code to keep this core module simple and small enough.

**Comment by AdoHe** [comment]
@tyaloo I decide to close this issue. I am not going to use Spring Ioc Container, it is much more complicated.
